version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017
    volumes:
      - ./scripts/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js:ro
